export const ADD_TO_TOPPINGMODAL = "ADD_TO_TOPPINGMODAL";
export const REMOVE_FROM_TOPPINGMODAL = "ADD_TO_TOPPINGMODAL";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
